spring:
  datasource:
    driverClassName: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost/backend?serverTimezone=America/Santiago
    username: root
    password: admin
  jpa:
    databasePlatform: org.hibernate.dialect.MySQLDialect
server:
  servlet:
    context-path: /api
springdoc:
  swagger-ui:
    path: /docs
logging:
  level:
    org.hibernate.SQL: DEBUG